### ISSUE TITLE
how to build it??

### ISSUE THREAD

**Issue by WJohnnyW** [botofancalin/ESP32_Camera_System#2]

**Comment by botofancalin** [comment]
Install visual studio code.
Install PlatformIO extension for VsCode.
Open the project folder on VsCode.
Build the projects.

**Comment by WJohnnyW** [comment]
Visual Studio is necessary? I only installed Vs Code

**Comment by WJohnnyW** [comment]
There are not wifi.h,wifi.c,esp_camera.h,esp_camera.c in Sender folder,I just can't find them

**Comment by botofancalin** [comment]
Did you install platformio on VsCode?
If you have everything installed, it should work just fine.
The files you are asking about are on [userprofile]\.platformio\packages\framework-arduinoespressif32\tools\sdk\include... folder on your PC

![camera system](https://user-images.githubusercontent.com/32721615/54480835-41bf4a00-4836-11e9-82c0-482b18b76543.jpg)
